spring.application.name=pathops-control-plane
server.servlet.context-path=/api

# Database Configuration
spring.datasource.url=${DB_CONNECTION_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_SHOW_SQL:false}

# Actuator
management.info.env.enabled=true
management.endpoints.web.exposure.include=health,info
info.git.commit=${GIT_COMMIT:unknown}
info.git.branch=${GIT_BRANCH:unknown}

# Spring Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${PATHOPS_AUTH_JWK_SET_URI}

#PathOps Auth Config
pathops.public.base-url=${PATHOPS_PUBLIC_BASE_URL}
pathops.auth.issuer=${PATHOPS_AUTH_ISSUER}
pathops.auth.client-id=${PATHOPS_AUTH_CLIENT_ID:control-plane-public}

#PathOps Vault
pathops.vault.base-url=${PATHOPS_VAULT_BASE_URL}
pathops.vault.token=${PATHOPS_VAULT_TOKEN}
pathops.vault.kv-mount=${PATHOPS_VAULT_KV_MOUNT:secret}