spring.application.name=pathops-control-plane
server.servlet.context-path=/api

# Database Configuration
spring.datasource.url=${DB_CONNECTION_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_SHOW_SQL:false}

# Actuator
management.info.env.enabled=true
management.endpoints.web.exposure.include=health,info
info.git.commit=${GIT_COMMIT:unknown}
info.git.branch=${GIT_BRANCH:unknown}

# Spring Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_URI}

# Debug
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.com.nimbusds=DEBUG
logging.level.org.springframework.web.client=DEBUG