apiVersion: v1
kind: Secret
metadata:
  name: control-plane-postgres-secret
  namespace: control-plane
type: Opaque
stringData:
  POSTGRES_DB: pathops_control_plane
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: CHANGE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: control-plane
  namespace: control-plane
type: Opaque
stringData:
  DB_USERNAME: admin
  DB_PASSWORD: CHANGE_ME
