apiVersion: v1
kind: ConfigMap
metadata:
  name: control-plane
  namespace: control-plane
data:
  DB_CONNECTION_URL: jdbc:postgresql://control-plane-postgres:5432/pathops_control_plane
  HIBERNATE_DDL_AUTO: "validate"
  JPA_SHOW_SQL: "false"
  PATHOPS_AUTH_JWK_SET_URI: "https://keycloak.demo.pathops.io/realms/pathops/protocol/openid-connect/certs"
  PATHOPS_PUBLIC_BASE_URL: "https://control-plane.demo.pathops.io"
  PATHOPS_AUTH_ISSUER: "https://keycloak.demo.pathops.io/realms/pathops"
  PATHOPS_AUTH_CLIENT_ID: "control-plane-public"
  PATHOPS_VAULT_BASE_URL: "https://vault.demo.pathops.io"
  PATHOPS_VAULT_KV_MOUNT: "secret"
  PATHOPS_DEMO_TOOLS_KEYCLOAK_BASE_URL: "https://keycloak.demo.pathops.io"
  PATHOPS_DEMO_TOOLS_JENKINS_BASE_URL: "https://jenkins.demo.pathops.io"
  PATHOPS_DEMO_BOOTSTRAP_ENABLED: "true"
