apiVersion: v1
kind: ConfigMap
metadata:
  name: control-plane
  namespace: control-plane
data:
  DB_CONNECTION_URL: jdbc:postgresql://control-plane-postgres:5432/pathops_control_plane
  HIBERNATE_DDL_AUTO: "validate"
  JPA_SHOW_SQL: "false"
  PATHOPS_AUTH_JWK_SET_URI: "https://keycloak.demo.pathops.io/realms/pathops/protocol/openid-connect/certs"
  PATHOPS_PUBLIC_BASE_URL: "https://control-plane.demo.pathops.io"
  PATHOPS_AUTH_ISSUER: "https://keycloak.demo.pathops.io/realms/pathops"
  PATHOPS_AUTH_CLIENT_ID: "control-plane-public"
  PATHOPS_EVENTS_PUBLISHING_ENABLED: "true"
  PATHOPS_RABBITMQ_HOST: "rabbitmq"
  PATHOPS_RABBITMQ_PORT: "5672"
  PATHOPS_RABBITMQ_VHOST: "/"
  PATHOPS_EVENTS_EXCHANGE: "pathops.events"
  PATHOPS_PROJECTOR_EVENTS_QUEUE: "pathops.projector.events"
  PATHOPS_TENANT_CREATED_ROUTING_KEY: "tenant.created"
  PATHOPS_OUTBOX_PUBLISHER_FIXED_DELAY_MS: "5000"
  PATHOPS_OUTBOX_PUBLISHER_BATCH_SIZE: "20"
