apiVersion: v1
kind: ConfigMap
metadata:
  name: control-plane
  namespace: control-plane
data:
  DB_CONNECTION_URL: jdbc:postgresql://control-plane-postgres:5432/pathops_control_plane
  HIBERNATE_DDL_AUTO: "validate"
  JPA_SHOW_SQL: "false"
  KEYCLOAK_JWK_URI: "https://keycloak.demo.pathops.io/realms/pathops/protocol/openid-connect/certs"
