apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: control-plane-postgres-data
  namespace: control-plane
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi