CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    issuer              VARCHAR(255) NOT NULL,
    subject             VARCHAR(255) NOT NULL,
    preferred_username  VARCHAR(255) NOT NULL,
    email               VARCHAR(255),
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_issuer_subject UNIQUE (issuer, subject)
);

CREATE TABLE tenants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_tenants_slug UNIQUE (slug)
);

CREATE TABLE memberships (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT NOT NULL,
    tenant_id   BIGINT NOT NULL,
    role        VARCHAR(32) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_memberships_user_tenant UNIQUE (user_id, tenant_id),
    CONSTRAINT ck_memberships_role
        CHECK (role IN ('OWNER', 'ADMIN', 'DEVELOPER', 'VIEWER')),
    CONSTRAINT fk_memberships_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_memberships_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE TABLE tools (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    tenant_id   BIGINT NOT NULL,
    created_by  BIGINT NOT NULL,
    type        VARCHAR(32) NOT NULL,
    provider    VARCHAR(32) NOT NULL,
    base_url    VARCHAR(2048) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_tools_name_tenant UNIQUE (name, tenant_id),
    CONSTRAINT ck_tools_type
        CHECK (type IN ('IDENTITY_PROVIDER', 'SCM', 'CI_CD', 'REGISTRY', 'OBSERVABILITY')),
    CONSTRAINT ck_tools_provider
        CHECK (provider IN ('KEYCLOAK', 'JENKINS', 'GITHUB_ACTIONS', 'GITLAB')),
    CONSTRAINT fk_tools_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_tools_created_by
        FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX ix_memberships_user_id
    ON memberships (user_id);

CREATE INDEX ix_memberships_tenant_id
    ON memberships (tenant_id);

CREATE INDEX ix_tools_tenant_id
    ON tools (tenant_id);