CREATE TABLE apps (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   BIGINT NOT NULL,
    name        VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_app_tenant_slug UNIQUE (tenant_id, slug)
);

CREATE TABLE memberships (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    role        VARCHAR(255) NOT NULL CHECK (role IN ('OWNER', 'ADMIN', 'DEVELOPER', 'VIEWER')),
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_membership_user_tenant UNIQUE (user_id, tenant_id)
);

CREATE TABLE pathops_users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subject             VARCHAR(255) NOT NULL,
    issuer              VARCHAR(255) NOT NULL,
    preferred_username  VARCHAR(255) NOT NULL,
    email               VARCHAR(255),
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_pathops_user_issuer_subject UNIQUE (issuer, subject)
);

CREATE TABLE tenants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL UNIQUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE apps
    ADD CONSTRAINT fk_apps_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants;

ALTER TABLE memberships
    ADD CONSTRAINT fk_memberships_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants;

ALTER TABLE memberships
    ADD CONSTRAINT fk_memberships_user
    FOREIGN KEY (user_id) REFERENCES pathops_users;