CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    issuer              VARCHAR(255) NOT NULL,
    subject             VARCHAR(255) NOT NULL,
    preferred_username  VARCHAR(255) NOT NULL,
    email               VARCHAR(255),
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_issuer_subject UNIQUE (issuer, subject)
);

CREATE TABLE tenants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_tenants_slug UNIQUE (slug)
);

CREATE TABLE memberships (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT NOT NULL,
    tenant_id   BIGINT NOT NULL,
    role        VARCHAR(32) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_memberships_user_tenant UNIQUE (user_id, tenant_id),
    CONSTRAINT ck_memberships_role
        CHECK (role IN ('OWNER', 'ADMIN', 'DEVELOPER', 'VIEWER')),
    CONSTRAINT fk_memberships_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_memberships_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE TABLE tools (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    tenant_id   BIGINT NOT NULL,
    created_by  BIGINT NOT NULL,
    type        VARCHAR(32) NOT NULL,
    provider    VARCHAR(32) NOT NULL,
    base_url    VARCHAR(2048) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_tools_name_tenant UNIQUE (name, tenant_id),
    CONSTRAINT ck_tools_type
        CHECK (type IN ('IDENTITY_PROVIDER', 'SCM', 'CI_CD', 'REGISTRY', 'OBSERVABILITY')),
    CONSTRAINT ck_tools_provider
        CHECK (provider IN ('KEYCLOAK', 'JENKINS', 'GITHUB_ACTIONS', 'GITLAB')),
    CONSTRAINT fk_tools_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_tools_created_by
        FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE TABLE tool_projection_configs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tool_id     BIGINT NOT NULL,
    scope       VARCHAR(32) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_tool_projection_configs_tool_scope UNIQUE (tool_id, scope),
    CONSTRAINT ck_tool_projection_configs_scope
        CHECK (scope IN ('TENANT', 'MEMBERSHIP')),
    CONSTRAINT fk_tool_projection_configs_tool
        FOREIGN KEY (tool_id) REFERENCES tools (id)
);

CREATE TABLE tenant_tool_projections (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tool_projection_config_id   BIGINT NOT NULL,
    status                      VARCHAR(32) NOT NULL,
    started_at                  TIMESTAMP(6) WITH TIME ZONE,
    finished_at                 TIMESTAMP(6) WITH TIME ZONE,
    duration_ms                 BIGINT,
    attempt_count               INTEGER,
    error_message               VARCHAR(4000),
    created_at                  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at                  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_tenant_tool_projections_config UNIQUE (tool_projection_config_id),
    CONSTRAINT ck_tenant_tool_projections_status
        CHECK (status IN ('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED')),
    CONSTRAINT fk_tenant_tool_projections_config
        FOREIGN KEY (tool_projection_config_id) REFERENCES tool_projection_configs (id)
);

CREATE TABLE membership_tool_projections (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    membership_id               BIGINT NOT NULL,
    tool_projection_config_id   BIGINT NOT NULL,
    status                      VARCHAR(32) NOT NULL,
    started_at                  TIMESTAMP(6) WITH TIME ZONE,
    finished_at                 TIMESTAMP(6) WITH TIME ZONE,
    duration_ms                 BIGINT,
    attempt_count               INTEGER,
    error_message               VARCHAR(4000),
    created_at                  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at                  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_membership_tool_projections_membership_config UNIQUE (membership_id, tool_projection_config_id),
    CONSTRAINT ck_membership_tool_projections_status
        CHECK (status IN ('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED')),
    CONSTRAINT fk_membership_tool_projections_membership
        FOREIGN KEY (membership_id) REFERENCES memberships (id),
    CONSTRAINT fk_membership_tool_projections_config
        FOREIGN KEY (tool_projection_config_id) REFERENCES tool_projection_configs (id)
);

CREATE INDEX ix_memberships_user_id
    ON memberships (user_id);

CREATE INDEX ix_memberships_tenant_id
    ON memberships (tenant_id);

CREATE INDEX ix_tools_tenant_id
    ON tools (tenant_id);

CREATE INDEX ix_tenant_tool_projections_status
    ON tenant_tool_projections (status);

CREATE INDEX ix_membership_tool_projections_status
    ON membership_tool_projections (status);