CREATE TABLE outbox_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id        UUID NOT NULL,
    event_type      VARCHAR(128) NOT NULL,
    aggregate_type  VARCHAR(128) NOT NULL,
    aggregate_id    VARCHAR(128) NOT NULL,
    exchange_name   VARCHAR(255) NOT NULL,
    routing_key     VARCHAR(255) NOT NULL,
    payload         TEXT NOT NULL,
    status          VARCHAR(32) NOT NULL,
    attempts        INTEGER NOT NULL DEFAULT 0,
    last_error      VARCHAR(4000),
    published_at    TIMESTAMP(6) WITH TIME ZONE,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_outbox_events_event_id UNIQUE (event_id),
    CONSTRAINT ck_outbox_events_status
        CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED'))
);

CREATE INDEX ix_outbox_events_status_created_at
    ON outbox_events (status, created_at);

CREATE INDEX ix_outbox_events_aggregate
    ON outbox_events (aggregate_type, aggregate_id);