ALTER TABLE pathops_users
    ADD COLUMN keycloak_user_id VARCHAR(255);
    
CREATE TABLE tenant_provisionings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    tool VARCHAR(50) NOT NULL,
    status VARCHAR(32) NOT NULL,
    last_attempt_at TIMESTAMP(6) WITH TIME ZONE,
    last_error VARCHAR(4000),
    external_ref VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT uk_tenant_tool UNIQUE (tenant_id, tool),
    CONSTRAINT fk_tp_tenant FOREIGN KEY (tenant_id) REFERENCES tenants
);