ALTER TABLE tenant_provisionings
    ADD COLUMN last_duration_ms BIGINT;

UPDATE tenant_provisionings
SET tool = 'KEYCLOAK_GROUP'
WHERE tool = 'KEYCLOAK';

UPDATE tenant_provisionings
SET tool = 'JENKINS_FOLDER'
WHERE tool = 'JENKINS';

CREATE TABLE membership_provisionings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id BIGINT NOT NULL,
    tool VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    last_attempt_at TIMESTAMP(6) WITH TIME ZONE,
    last_duration_ms BIGINT,
    last_error VARCHAR(4000),
    external_ref VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT uk_membership_tool UNIQUE (membership_id, tool),
    CONSTRAINT fk_mp_membership FOREIGN KEY (membership_id) REFERENCES memberships
);

CREATE TABLE provisioning_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(32) NOT NULL,
    tenant_provisioning_id BIGINT,
    membership_provisioning_id BIGINT,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP(6) WITH TIME ZONE,
    heartbeat_at TIMESTAMP(6) WITH TIME ZONE,
    finished_at TIMESTAMP(6) WITH TIME ZONE,
    duration_ms BIGINT,
    error_message VARCHAR(4000),
    external_ref VARCHAR(255),
    claimed_by VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT ck_provisioning_jobs_scope
        CHECK (
            (scope_type = 'TENANT' AND tenant_provisioning_id IS NOT NULL AND membership_provisioning_id IS NULL)
            OR
            (scope_type = 'MEMBERSHIP' AND membership_provisioning_id IS NOT NULL AND tenant_provisioning_id IS NULL)
        ),

    CONSTRAINT fk_pj_tenant_provisioning FOREIGN KEY (tenant_provisioning_id) REFERENCES tenant_provisionings,
    CONSTRAINT fk_pj_membership_provisioning FOREIGN KEY (membership_provisioning_id) REFERENCES membership_provisionings
);

CREATE INDEX idx_provisioning_jobs_status_created_at
    ON provisioning_jobs(status, created_at);